// Generated by CoffeeScript 1.11.1
(function() {
  var Cmd, Fork, async;

  Fork = require('../fork-func');

  async = function(arg) {
    return arg + '!!!';
  };

  Cmd = (function() {
    function Cmd(arg) {
      if (this === global) {
        return async(arg);
      }
    }

    Cmd.prototype.execute = function(arg) {
      Fork(__filename, arg, (function(_this) {
        return function(error, result) {
          if (error) {
            return console.log('test error: ', error);
          } else {
            return console.log('test result: ', result);
          }
        };
      })(this));
      return null;
    };

    return Cmd;

  })();

  module.exports = Cmd;

}).call(this);
